import type { Metadata } from "next";
import "./global.css";
import Provider from "@/Provider";


export const metadata: Metadata = {
  title: "SK_MART",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-screen bg-linear-to-b from-green-50 to-white">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
