import type { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  title: "SK_MART",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-screen bg-linear-to-b from-green-100 to-white" >
        {children}
      </body>
    </html>
  );
}
